-- MySQL Script generated by MySQL Workbench
-- Thu Apr 16 16:53:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema delilah
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema delilah
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `delilah` DEFAULT CHARACTER SET utf8mb4 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `delilah` ;

-- -----------------------------------------------------
-- Table `delilah`.`Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`Rol` ;

CREATE TABLE IF NOT EXISTS `delilah`.`Rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `descrip` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah`.`Province`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`Province` ;

CREATE TABLE IF NOT EXISTS `delilah`.`Province` (
  `id_province` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_province`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah`.`City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`City` ;

CREATE TABLE IF NOT EXISTS `delilah`.`City` (
  `id_city` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `id_province` INT NOT NULL,
  PRIMARY KEY (`id_city`),
  INDEX `fk_id_province_city_idx` (`id_province` ASC) ,
  CONSTRAINT `fk_id_province_city`
    FOREIGN KEY (`id_province`)
    REFERENCES `delilah`.`Province` (`id_province`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`User` ;

CREATE TABLE IF NOT EXISTS `delilah`.`User` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `token` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `last_name` VARCHAR(60) NOT NULL,
  `adress` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `id_rol` INT NOT NULL,
  `id_city` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `id_rol_idx` (`id_rol` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `fk_id_city_user_idx` (`id_city` ASC) ,
  CONSTRAINT `fk_id_rol_user`
    FOREIGN KEY (`id_rol`)
    REFERENCES `delilah`.`Rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_city_user`
    FOREIGN KEY (`id_city`)
    REFERENCES `delilah`.`City` (`id_city`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`Product` ;

CREATE TABLE IF NOT EXISTS `delilah`.`Product` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`id_product`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah`.`Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`Payment` ;

CREATE TABLE IF NOT EXISTS `delilah`.`Payment` (
  `id_payment` INT NOT NULL AUTO_INCREMENT,
  `descrip` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_payment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah`.`Order_State`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`Order_State` ;

CREATE TABLE IF NOT EXISTS `delilah`.`Order_State` (
  `id_state` INT NOT NULL AUTO_INCREMENT,
  `Descrip` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_state`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`Order` ;

CREATE TABLE IF NOT EXISTS `delilah`.`Order` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_payment` INT NOT NULL,
  `time` DATETIME NULL default current_timestamp,
  `id_state` INT NOT NULL,
  PRIMARY KEY (`id_order`),
  INDEX `id_user_idx` (`id_user` ASC) ,
  INDEX `id_payment_idx` (`id_payment` ASC) ,
  INDEX `id_state_idx` (`id_state` ASC) ,
  CONSTRAINT `fk_id_user_order`
    FOREIGN KEY (`id_user`)
    REFERENCES `delilah`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_payment_order`
    FOREIGN KEY (`id_payment`)
    REFERENCES `delilah`.`Payment` (`id_payment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_state_order`
    FOREIGN KEY (`id_state`)
    REFERENCES `delilah`.`Order_State` (`id_state`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delilah`.`Order_Detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`Order_Detail` ;

CREATE TABLE IF NOT EXISTS `delilah`.`Order_Detail` (
  `id_order_detail` INT NOT NULL AUTO_INCREMENT,
  `id_product` INT NOT NULL,
  `quantity` INT NOT NULL,
  `subtotal` FLOAT NOT NULL,
  `id_order` INT NOT NULL,
  PRIMARY KEY (`id_order_detail`),
  INDEX `id_order_idx` (`id_order` ASC) ,
  INDEX `fk_id_product_detail_idx` (`id_product` ASC) ,
  CONSTRAINT `fk_id_product_detail`
    FOREIGN KEY (`id_product`)
    REFERENCES `delilah`.`Product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_order_detail`
    FOREIGN KEY (`id_order`)
    REFERENCES `delilah`.`Order` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `delilah`.`Favorite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `delilah`.`Favorite` ;

CREATE TABLE IF NOT EXISTS `delilah`.`Favorite` (
  `id_favorite` INT NOT NULL AUTO_INCREMENT,
  `id_product` INT NOT NULL,
  `id_user` INT NOT NULL,
  INDEX `id_product_idx` (`id_product` ASC) ,
  INDEX `id_user_idx` (`id_user` ASC) ,
  PRIMARY KEY (`id_favorite`),
  CONSTRAINT `fk_id_product_favorite`
    FOREIGN KEY (`id_product`)
    REFERENCES `delilah`.`Product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_user_favorite`
    FOREIGN KEY (`id_user`)
    REFERENCES `delilah`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Data for table `delilah`.`Rol`
-- -----------------------------------------------------
START TRANSACTION;
USE `delilah`;
INSERT INTO `delilah`.`Rol` (`id_rol`, `descrip`) VALUES (1, 'administrador');
INSERT INTO `delilah`.`Rol` (`id_rol`, `descrip`) VALUES (2, 'usuario');

COMMIT;
-- -----------------------------------------------------
-- Data for table `delilah`.`Province`
-- -----------------------------------------------------
START TRANSACTION;
USE `delilah`;
INSERT INTO `delilah`.`Province` (`name`) VALUES ('Buenos Aires');
INSERT INTO `delilah`.`Province` (`name`) VALUES ('Córdoba');
INSERT INTO `delilah`.`Province` (`name`) VALUES ('Mendoza');
INSERT INTO `delilah`.`Province` (`name`) VALUES ('Santa Fe');
COMMIT;
-- -----------------------------------------------------
-- Data for table `delilah`.`City`
-- -----------------------------------------------------
START TRANSACTION;
USE `delilah`;
INSERT INTO `delilah`.`City` (`name`, `id_province`) VALUES ('Ciudad Autónoma',1);
INSERT INTO `delilah`.`City` (`name`, `id_province`) VALUES ('Capital',2);
INSERT INTO `delilah`.`City` (`name`, `id_province`) VALUES ('San Rafael',3);
INSERT INTO `delilah`.`City` (`name`, `id_province`) VALUES ('Rosario',4);
COMMIT;

-- -----------------------------------------------------
-- Data for table `delilah`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `delilah`;
INSERT INTO `delilah`.`User` (`id_user`, `username`,`email`,`token`,`password`, `name`, `last_name`, `adress`, `phone`, `id_rol`, `id_city`) VALUES (1, 'juancho', 'juan@gmail.com', null, '1234', 'Juan', 'Perez', 'Gallardo Comun 1963', '383 555 9953', 1, 3);
INSERT INTO `delilah`.`User` (`id_user`, `username`,`email`,`token`,`password`, `name`, `last_name`, `adress`, `phone`, `id_rol`, `id_city`) VALUES (2, 'josepepe', 'jose@gmail.com', null, '1234','Jose', 'Gomez', 'Av. de las Riveras 17653 2B', '351 666 7893', 2, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `delilah`.`Product`
-- -----------------------------------------------------
START TRANSACTION;
USE `delilah`;
INSERT INTO `delilah`.`Product` (`id_product`, `name`, `price`) VALUES (1, 'costeleta con papas', 350);
INSERT INTO `delilah`.`Product` (`id_product`, `name`, `price`) VALUES (2, 'pizza de rucula', 390);
INSERT INTO `delilah`.`Product` (`id_product`, `name`, `price`) VALUES (3, 'lomito criollo', 450);

COMMIT;


-- -----------------------------------------------------
-- Data for table `delilah`.`Payment`
-- -----------------------------------------------------
START TRANSACTION;
USE `delilah`;
INSERT INTO `delilah`.`Payment` (`id_payment`, `descrip`) VALUES (1, 'efectivo');
INSERT INTO `delilah`.`Payment` (`id_payment`, `descrip`) VALUES (2, 'tarjeta de credito');
INSERT INTO `delilah`.`Payment` (`id_payment`, `descrip`) VALUES (3, 'tarjeta de debito');

COMMIT;


-- -----------------------------------------------------
-- Data for table `delilah`.`Order_State`
-- -----------------------------------------------------
START TRANSACTION;
USE `delilah`;
INSERT INTO `delilah`.`Order_State` (`id_state`, `Descrip`) VALUES (1, 'nuevo');
INSERT INTO `delilah`.`Order_State` (`id_state`, `Descrip`) VALUES (2, 'confirmado');
INSERT INTO `delilah`.`Order_State` (`id_state`, `Descrip`) VALUES (3, 'preparando');
INSERT INTO `delilah`.`Order_State` (`id_state`, `Descrip`) VALUES (4, 'enviando');
INSERT INTO `delilah`.`Order_State` (`id_state`, `Descrip`) VALUES (5, 'entregado');

COMMIT;


-- -----------------------------------------------------
-- Data for table `delilah`.`Favorite`
-- -----------------------------------------------------
START TRANSACTION;
USE `delilah`;
INSERT INTO `delilah`.`Favorite` (`id_favorite`, `id_product`, `id_user`) VALUES (1, 1, 2);

COMMIT;

